version: 2
updates:
  - package-ecosystem: "bun"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: 0 5 * * *
      timezone: Asia/Hong_Kong
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
