name: Build and Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    name: Astro Check
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2.0.2
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Run Astro Check
        run: bun astro check
  build:
    runs-on: ubuntu-latest
    name: Astro Build
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2.0.2
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Run Astro Build
        run: bun astro build
