name: Code Quality Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  code-quality-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
      - name: Setup Biome
        uses: biomejs/setup-biome@v2.6.0
        with:
          version: latest
      - name: Run Biome
        run: biome ci ./src --reporter=github
