name: Purge Cache

on:
  push:
    branches:
      - main

jobs:
  purge-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Purge Cloudflare Cache
        env:
          CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        run: |
          HTTP_RESPONSE=$(curl -sS "https://api.cloudflare.com/client/v4/zones/${CF_ZONE_ID}/purge_cache" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${CF_API_TOKEN}" \
            -w "HTTP_STATUS:%{http_code}" \
            -d '{"purge_everything": true}' \
            "$@")

          HTTP_BODY=$(echo "${HTTP_RESPONSE}" | sed -E 's/HTTP_STATUS\:[0-9]{3}$//')
          HTTP_STATUS=$(echo "${HTTP_RESPONSE}" | tr -d '\n' | sed -E 's/.*HTTP_STATUS:([0-9]{3})$/\1/')

          if [ "${HTTP_STATUS}" -eq "200" ]; then
            echo "Successfully purged!"
            exit 0
          else
            echo "Purge failed. API response was: "
            echo "${HTTP_BODY}"
            exit 1
          fi